// Generated by gencpp from file nav_command/NavCmd.msg
// DO NOT EDIT!


#ifndef NAV_COMMAND_MESSAGE_NAVCMD_H
#define NAV_COMMAND_MESSAGE_NAVCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav_command
{
template <class ContainerAllocator>
struct NavCmd_
{
  typedef NavCmd_<ContainerAllocator> Type;

  NavCmd_()
    : start_nav(false)
    , target_x(0.0)
    , target_y(0.0)
    , target_yaw(0.0)
    , robot_id()  {
    }
  NavCmd_(const ContainerAllocator& _alloc)
    : start_nav(false)
    , target_x(0.0)
    , target_y(0.0)
    , target_yaw(0.0)
    , robot_id(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _start_nav_type;
  _start_nav_type start_nav;

   typedef double _target_x_type;
  _target_x_type target_x;

   typedef double _target_y_type;
  _target_y_type target_y;

   typedef double _target_yaw_type;
  _target_yaw_type target_yaw;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::nav_command::NavCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_command::NavCmd_<ContainerAllocator> const> ConstPtr;

}; // struct NavCmd_

typedef ::nav_command::NavCmd_<std::allocator<void> > NavCmd;

typedef boost::shared_ptr< ::nav_command::NavCmd > NavCmdPtr;
typedef boost::shared_ptr< ::nav_command::NavCmd const> NavCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_command::NavCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_command::NavCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav_command::NavCmd_<ContainerAllocator1> & lhs, const ::nav_command::NavCmd_<ContainerAllocator2> & rhs)
{
  return lhs.start_nav == rhs.start_nav &&
    lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y &&
    lhs.target_yaw == rhs.target_yaw &&
    lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav_command::NavCmd_<ContainerAllocator1> & lhs, const ::nav_command::NavCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nav_command::NavCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_command::NavCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_command::NavCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_command::NavCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_command::NavCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_command::NavCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_command::NavCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49a73690f439fc687c4e207d9765b972";
  }

  static const char* value(const ::nav_command::NavCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49a73690f439fc68ULL;
  static const uint64_t static_value2 = 0x7c4e207d9765b972ULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_command::NavCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_command/NavCmd";
  }

  static const char* value(const ::nav_command::NavCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_command::NavCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 导航指令消息\n"
"bool start_nav       # 是否启动导航（true=启动，false=停止）\n"
"float64 target_x     # 目标点 x 坐标（map 坐标系）\n"
"float64 target_y     # 目标点 y 坐标（map 坐标系）\n"
"float64 target_yaw   # 目标点偏航角（弧度）\n"
"string robot_id      # 目标机器人 ID（区分发给 A/B）\n"
;
  }

  static const char* value(const ::nav_command::NavCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_command::NavCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_nav);
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.target_yaw);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_command::NavCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_command::NavCmd_<ContainerAllocator>& v)
  {
    s << indent << "start_nav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_nav);
    s << indent << "target_x: ";
    Printer<double>::stream(s, indent + "  ", v.target_x);
    s << indent << "target_y: ";
    Printer<double>::stream(s, indent + "  ", v.target_y);
    s << indent << "target_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.target_yaw);
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_COMMAND_MESSAGE_NAVCMD_H
